export const GET_ALL_APPROVALS = 'GET_ALL_APPROVALS';
export const GET_SINGLE_APPROVAL = 'GET_SINGLE_APPROVAL';
export const CONVERT_APPROVAL_TO_USER = 'CONVERT_APPROVAL_TO_USER';
export const LOADING = 'LOADING';
export const CREATE_APPROVAL = 'CREATE_APPROVAL';
export const EDIT_APPROVAL = 'EDIT_APPROVAL';
export const COMFIRM_APPROVAL = 'COMFIRM_APPROVAL';
