export const ALL_INVOICE = 'ALL_INVOICE';
export const GET_SINGLE_INVOICE = 'GET_SINGLE_INVOICE';
export const GET_TOTAL_STATUS_INVOICE = 'GET_TOTAL_STATUS_INVOICE';
export const LOADING = 'LOADING';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
