export const GET_ALL_SCHEDULED_MAINTENANCE = 'GET_ALL_SCHEDULED_MAINTENANCE';
export const GET_ALL_ASSET = 'GET_ALL_ASSET';
export const GET_ALL_VENDORS = 'GET_ALL_VENDORS';
export const LOADING = 'LOADING';
export const CREATE_MAINTENANCE = 'CREATE_MAINTENANCE';
