export const LOADING = 'LOADING';

// PAYROLL

export const GET_ALL_PAYROLL = 'GET_ALL_PAYROLL';

export const GET_SINGLE_PAYROLL = 'GET_SINGLE_PAYROLL';

export const GET_CURRENT_USER_PAYROLL = 'GET_CURRENT_USER_PAYROLL';

export const CREATE_PAYROLL = 'CREATE_PAYROLL';

export const EDIT_PAYROLL = 'EDIT_PAYROLL';
export const DELETE_PAYROLL = 'DELETE_PAYROLL';

// PAYSLIP
export const GET_ALL_PAYSLIP = 'GET_ALL_PAYSLIP';

export const GET_SINGLE_PAYSLIP = 'GET_SINGLE_PAYSLIP';

export const DELETE_PAYSLIP = 'DELETE_PAYSLIP';

export const CREATE_PAYSLIP = 'CREATE_PAYSLIP';

export const EDIT_PAYSLIP = 'EDIT_PAYSLIP';
export const GET_CURRENT_USER_PAYSLIP = 'GET_CURRENT_USER_PAYSLIP';

// POSITION
export const GET_ALL_POSITION = 'GET_ALL_POSITION';

export const GET_SINGLE_POSITION = 'GET_SINGLE_POSITION';

export const GET_CURRENT_USER_POSITION = 'GET_CURRENT_USER_POSITION';

export const CREATE_POSITION = 'CREATE_POSITION';

export const EDIT_POSITION = 'EDIT_POSITION';

export const DELETE_POSITION = 'DELETE_POSITION';

// ALLOWANCE
export const GET_ALL_ALLOWANCE = 'GET_ALL_ALLOWANCE';

export const GET_SINGLE_ALLOWANCE = 'GET_SINGLE_ALLOWANCE';

export const GET_CURRENT_USER_ALLOWANCE = 'GET_CURRENT_USER_ALLOWANCE';

export const CREATE_ALLOWANCE = 'CREATE_ALLOWANCE';

export const EDIT_ALLOWANCE = 'EDIT_ALLOWANCE';

export const DELETE_ALLOWANCE = 'DELETE_ALLOWANCE';

// BONUS
export const GET_ALL_BONUSES = 'GET_ALL_BONUSES';

export const GET_SINGLE_BONUS = 'GET_SINGLE_BONUS';

export const GET_CURRENT_USER_BONUS = 'GET_CURRENT_USER_BONUS';

export const CREATE_BONUS = 'CREATE_BONUS';

export const EDIT_BONUS = 'EDIT_BONUS';

export const DELETE_BONUS = 'DELETE_BONUS';

// ALLOWED DEDUCTION
export const GET_ALL_ALLOWED_DEDUCTION = 'GET_ALL_ALLOWED_DEDUCTION';

export const GET_SINGLE_ALLOWED_DEDUCTION = 'GET_SINGLE_ALLOWED_DEDUCTION';

export const GET_CURRENT_USER_ALLOWED_DEDUCTION = 'GET_CURRENT_USER_ALLOWED_DEDUCTION';

export const CREATE_ALLOWED_DEDUCTION = 'CREATE_ALLOWED_DEDUCTION';

export const EDIT_ALLOWED_DEDUCTION = 'EDIT_ALLOWED_DEDUCTION';

export const DELETE_ALLOWED_DEDUCTION = 'DELETE_ALLOWED_DEDUCTION';

// EMPLOYEE DEDUCTION
export const GET_ALL_EMPLOYEE_DEDUCTION = 'GET_ALL_EMPLOYEE_DEDUCTION';

export const GET_SINGLE_EMPLOYEE_DEDUCTION = 'GET_SINGLE_EMPLOYEE_DEDUCTION';

export const GET_CURRENT_USER_EMPLOYEE_DEDUCTION = 'GET_CURRENT_USER_EMPLOYEE_DEDUCTION';

export const CREATE_EMPLOYEE_DEDUCTION = 'CREATE_EMPLOYEE_DEDUCTION';

export const EDIT_EMPLOYEE_DEDUCTION = 'EDIT_EMPLOYEE_DEDUCTION';

export const DELETE_EMPLOYEE_DEDUCTION = 'DELETE_EMPLOYEE_DEDUCTION';

// EMPLOYER DEDUCTION
export const GET_ALL_EMPLOYER_DEDUCTION = 'GET_ALL_EMPLOYER_DEDUCTION';

export const GET_SINGLE_EMPLOYER_DEDUCTION = 'GET_SINGLE_EMPLOYER_DEDUCTION';

export const GET_CURRENT_USER_EMPLOYER_DEDUCTION = 'GET_CURRENT_USER_EMPLOYER_DEDUCTION';

export const CREATE_EMPLOYER_DEDUCTION = 'CREATE_EMPLOYER_DEDUCTION';

export const EDIT_EMPLOYER_DEDUCTION = 'EDIT_EMPLOYER_DEDUCTION';

export const DELETE_EMPLOYER_DEDUCTION = 'DELETE_EMPLOYER_DEDUCTION';
