export const LOADING = 'LOADING';
export const GET_ALL_PRIVILEGE = 'GET_ALL_PRIVILEGE';
export const GET_ALL_PRIVILEGE_BY_ID = 'GET_ALL_PRIVILEGE_BY_ID';
export const CREATE_PRIVILEGE = 'CREATE_PRIVILEGE';
export const EDIT_PRIVILEGE = 'EDIT_PRIVILEGE';
export const DELETE_PRIVILEGE = 'DELETE_PRIVILEGE';
export const CONFIRM_PRIVILEGE = 'CONFIRM_PRIVILEGE';
