export const ALL_RECEIPTS = 'ALL_RECEIPTS';
export const GET_SINGLE_RECEIPTS = 'GET_SINGLE_RECEIPTS';
export const GET_TOTAL_STATUS_RECEIPTS = 'GET_TOTAL_STATUS_RECEIPTS';
export const GET_SINGLE_STATUS_RECEIPTS = 'GET_SINGLE_STATUS_RECEIPTS';
export const LOADING = 'LOADING';
export const CREATE_RECEIPTS = 'CREATE_RECEIPTS';
export const UPDATE_RECEIPTS = 'UPDATE_RECEIPTS';
export const DELETE_RECEIPTS = 'DELETE_RECEIPTS';
